'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Esy_POS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Add_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add-New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BarCode_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarCode-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BarCode_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarCode-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beverage_Coffee_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beverage-Coffee-03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Black_List_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Black List-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cash_sm_transfer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cash-sm-transfer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Certificate_Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Certificate-Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Certificate_Information_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Certificate-Information-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Check_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Check-03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cheque_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cheque-01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Circle_Close___01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Circle Close - 01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cross_Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Customer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Customer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Customer_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Customer-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Data_Erase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Data-Erase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Data_previous_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Data previous-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database_Connection_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database Connection-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Database_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property date_wise_sls_crt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("date-wise-sls-crt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dettol_original_125gm_160x160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dettol_original_125gm-160x160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editdta_pencil_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editdta-pencil-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Employee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Employee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Employee_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Employee-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Employee_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Employee-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exit___01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit - 01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exit_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exit_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exp_refund_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exp-refund-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property File_Add_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("File Add-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire_Exit_01_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire Exit-01-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire_Exit_01_WF1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire Exit-01-WF1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Folder_Add_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder-Add-03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Form_04_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Form-04-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Form_06_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Form-06-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Form_06_WF_smoke() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Form-06-WF-smoke", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Garbage_Open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Garbage-Open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Garbage_Open_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Garbage-Open-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hide_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hide-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inc_money_pound_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inc-money-pound-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Info_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Login_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login-01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Login_01_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login-01-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property microsoft_excel_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microsoft-excel-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_image_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_image_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_item_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_item_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_item_image_sm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_item_image_sm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_item_image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_item_image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_item_image2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_item_image2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paid_Invoice1_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paid Invoice1-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paid_Invoice1_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paid Invoice1-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paper_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paper-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pending_Invoice_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pending Invoice-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Photograph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Photograph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Power_Off_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Power Off-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Print_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Printer_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Printer_WF_fil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer-WF-fil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Product4_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Product4-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Product4_WF_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Product4-WF-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Road_01_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Road-01-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sales_Order() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sales-Order", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sales_Order_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sales-Order-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sales_Order_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sales Order-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_01_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save-01-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_01_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save-01-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Select_List() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Select List", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings-02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield-02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shopping_Basket_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shopping-Basket-01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shopping_Cart_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shopping Cart-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sm_accounting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sm-accounting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sm_vou_dollar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sm-vou-dollar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stock_Index_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stock-Index-Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stock_Index_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stock-Index Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stock_Index_Up_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stock-Index Up-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stock_Index_Up_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stock-Index Up-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Submit_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Submit-02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supplier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supplier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supplier_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supplier-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supplier_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supplier-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tag5_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tag5-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tag5_WF_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tag5-WF-lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Th_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Th list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property To_Do_List_1_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("To Do List 1-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tomato_160x160_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tomato-160x160 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Modify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-Modify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Modify_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-Modify-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Save_02_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Save-02-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Settings_02_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Settings-02-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Settings_02_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Settings-02-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Unlocked_01_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Unlocked-01-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property View_List_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View List-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property View_List_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View List-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vou_sm_incomes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vou_sm_incomes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wand_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wand-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Warning___02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning - 02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wrong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wrong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wrong_WF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wrong-WF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wrong_WF_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wrong-WF-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
